services:
  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: My-broker
    ports:
      - "${KAFKA_PORT:-9092}:9092"
    environment:
      # Настройки KRaft
      KAFKA_NODE_ID: ${KAFKA_NODE_ID:-1}
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:29093'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      
      # Слушатели
      KAFKA_LISTENERS: 'PLAINTEXT://0.0.0.0:29092,PLAINTEXT_HOST://0.0.0.0:9092,CONTROLLER://0.0.0.0:29093'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:${KAFKA_INTERNAL_PORT:-29092},PLAINTEXT_HOST://localhost:${KAFKA_PORT:-9092}'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      
      # Идентификатор кластера (обязателен для KRaft)
      # Можно сгенерировать любой случайный Base64 или оставить этот
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'
      
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    healthcheck:
      test: ["CMD", "kafka-broker-api-versions", "--bootstrap-server", "localhost:9092"]
      interval: 5s   
      timeout: 10s  
      retries: 3
      start_period: 15s  

  console:
    image: docker.redpanda.com/redpandadata/console:latest
    container_name: redpanda-console
    environment:
      KAFKA_BROKERS: "kafka:${KAFKA_INTERNAL_PORT:-29092}"
    ports:
      - "8080:8080"
    depends_on:
      - kafka

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse-server
    env_file:
      - .env
    environment:
      - CLICKHOUSE_USER=${CH_USER}
      - CLICKHOUSE_PASSWORD=${CH_PASSWORD}
      - CLICKHOUSE_DB=${CH_DB}
    ports:
      - "8123:8123"
      - "8443:8443"
      - "9000:9000"
    user: "0:0"
    volumes:
      - ./ch_config/clickhouse.crt:/etc/clickhouse-server/config.d/clickhouse.crt:ro
      - ./ch_config/clickhouse.key:/etc/clickhouse-server/config.d/clickhouse.key:ro
      - ./ch_config/custom_ssl.xml:/etc/clickhouse-server/config.d/ssl-config.xml:ro
      - clickhouse_data:/var/lib/clickhouse
    healthcheck:
      test: ["CMD", "clickhouse-client", "--user", "${CH_USER}", "--password", "${CH_PASSWORD}", "--query", "SELECT 1"]
      interval: 5s
      timeout: 10s
      retries: 3
      start_period: 15s

  grafana:
    user: "0:0"
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
      - GF_INSTALL_PLUGINS=vertamedia-clickhouse-datasource
    depends_on:
      - clickhouse
    volumes:
      - grafana_data:/var/lib/grafana
      - ./provisioning_datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
      - ./provisioning_dashboards.yaml:/etc/grafana/provisioning/dashboards/provisioning.yaml
      - ./dashboards:/etc/grafana/provisioning/dashboards/files

  # Продюсер криптовалют (Binance)
  crypto-producer:
    build: .
    container_name: crypto-producer
    command: python app/producer.py
    env_file: .env
    environment:
      - KAFKA_SERVER=kafka:29092
    depends_on:
      kafka:
        condition: service_healthy

  # Продюсер акций (Finnhub)
  stocks-producer:
    build: .
    container_name: stocks-producer
    command: python app/producer_stocks.py
    env_file: .env
    environment:
      - KAFKA_SERVER=kafka:29092
    depends_on:
      kafka:
        condition: service_healthy

  # Консьюмер (Запись в ClickHouse)
  consumer:
    build: .
    container_name: crypto-consumer
    command: python app/consumer.py
    env_file: .env
    environment:
      - KAFKA_SERVER=kafka:29092
      - CH_HOST=clickhouse-server
      - CH_PORT=8443
    depends_on:
      kafka:
        condition: service_healthy
      clickhouse:
        condition: service_healthy

volumes:
  clickhouse_data:
  grafana_data: