{
 "title": "Cripto Live",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Изменение цены за последние 24 часа",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "contextWindowSize": "10",
     "formattedQuery": "/* grafana dashboard='Cripto Live', user=1 */\nSELECT\r\n    symbol AS \"Монеты\",\r\n    argMax(price, timestamp) AS \"Текущая цена\",\r\n    argMax(priceChangePercent, timestamp) AS \"Изменение за 24 часа в (%)\",\r\n    argMax(priceChange, timestamp) AS \"Изменение за 24 часа в ($)\",\r\n    max(toTimeZone(parseDateTimeBestEffort(timestamp), 'Europe/Moscow')) AS \"Последнее обновление\"\r\nFROM default.Prices\r\nGROUP BY symbol\r\nORDER BY \"Монеты\" ASC",
     "query": "SELECT\r\n    symbol AS \"Монеты\",\r\n    argMax(price, timestamp) AS \"Текущая цена\",\r\n    argMax(priceChangePercent, timestamp) AS \"Изменение за 24 часа в (%)\",\r\n    argMax(priceChange, timestamp) AS \"Изменение за 24 часа в ($)\",\r\n    max(toTimeZone(parseDateTimeBestEffort(timestamp), 'Europe/Moscow')) AS \"Последнее обновление\"\r\nFROM default.Prices\r\nGROUP BY symbol\r\nORDER BY \"Монеты\" ASC",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Binance Coin(BNB) ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "contextWindowSize": "10",
     "formattedQuery": "/* grafana dashboard='Cripto Live', user=1 */\nSELECT\r\n    toTimeZone(parseDateTimeBestEffort(timestamp), 'Europe/Moscow') AS time,\r\n    price AS BNB\r\nFROM default.Prices\r\nWHERE symbol = 'BNB'\r\nORDER BY time ASC",
     "query": "SELECT\r\n    toTimeZone(parseDateTimeBestEffort(timestamp), 'Europe/Moscow') AS time,\r\n    price AS BNB\r\nFROM default.Prices\r\nWHERE symbol = 'BNB'\r\nORDER BY time ASC",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Solana(SOL)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "contextWindowSize": "10",
     "formattedQuery": "/* grafana dashboard='Cripto Live', user=1 */\nSELECT\r\n    toTimeZone(parseDateTimeBestEffort(timestamp), 'Europe/Moscow') AS time,\r\n    price AS SOL\r\nFROM default.Prices\r\nWHERE symbol = 'SOL'\r\nORDER BY time ASC",
     "query": "SELECT\r\n    toTimeZone(parseDateTimeBestEffort(timestamp), 'Europe/Moscow') AS time,\r\n    price AS SOL\r\nFROM default.Prices\r\nWHERE symbol = 'SOL'\r\nORDER BY time ASC",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Ethereum(ETH)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "contextWindowSize": "10",
     "formattedQuery": "/* grafana dashboard='Cripto Live', user=1 */\nSELECT\r\n    toTimeZone(parseDateTimeBestEffort(timestamp), 'Europe/Moscow') AS time,\r\n    price AS ETH\r\nFROM default.Prices\r\nWHERE symbol = 'ETH'\r\nORDER BY time ASC",
     "query": "SELECT\r\n    toTimeZone(parseDateTimeBestEffort(timestamp), 'Europe/Moscow') AS time,\r\n    price AS ETH\r\nFROM default.Prices\r\nWHERE symbol = 'ETH'\r\nORDER BY time ASC",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Bitcoin (BTC)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "contextWindowSize": "10",
     "formattedQuery": "/* grafana dashboard='Cripto Live', user=1 */\nSELECT\r\n    toTimeZone(parseDateTimeBestEffort(timestamp), 'Europe/Moscow') AS time,\r\n    price AS BTC\r\nFROM default.Prices\r\nWHERE symbol = 'BTC'\r\nORDER BY time ASC",
     "query": "SELECT\r\n    toTimeZone(parseDateTimeBestEffort(timestamp), 'Europe/Moscow') AS time,\r\n    price AS BTC\r\nFROM default.Prices\r\nWHERE symbol = 'BTC'\r\nORDER BY time ASC",
     "round": "0s"
    }
   ]
  }
 ]
}