{
 "title": "Stocks Live",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Qualcomm (QCOM)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "contextWindowSize": "10",
     "formattedQuery": "/* grafana dashboard='Stocks Live', user=1 */\nSELECT\r\n    toTimeZone(parseDateTimeBestEffort(timestamp), 'Europe/Moscow') AS time,\r\n    price AS QCOM\r\nFROM default.Stocks_Price\r\nWHERE symbol = 'QCOM'\r\nORDER BY time ASC",
     "query": "SELECT\r\n    toTimeZone(parseDateTimeBestEffort(timestamp), 'Europe/Moscow') AS time,\r\n    price AS QCOM\r\nFROM default.Stocks_Price\r\nWHERE symbol = 'QCOM'\r\nORDER BY time ASC",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Microsoft (MSFT)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "contextWindowSize": "10",
     "formattedQuery": "/* grafana dashboard='Stocks Live', user=1 */\nSELECT\r\n    toTimeZone(parseDateTimeBestEffort(timestamp), 'Europe/Moscow') AS time,\r\n    price AS MSFT\r\nFROM default.Stocks_Price\r\nWHERE symbol = 'MSFT'\r\nORDER BY time ASC",
     "query": "SELECT\r\n    toTimeZone(parseDateTimeBestEffort(timestamp), 'Europe/Moscow') AS time,\r\n    price AS MSFT\r\nFROM default.Stocks_Price\r\nWHERE symbol = 'MSFT'\r\nORDER BY time ASC",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Nvidia (NVDA)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "contextWindowSize": "10",
     "formattedQuery": "/* grafana dashboard='Stocks Live', user=1 */\nSELECT\r\n    toTimeZone(parseDateTimeBestEffort(timestamp), 'Europe/Moscow') AS time,\r\n    price AS NVDA\r\nFROM default.Stocks_Price\r\nWHERE symbol = 'NVDA'\r\nORDER BY time ASC",
     "query": "SELECT\r\n    toTimeZone(parseDateTimeBestEffort(timestamp), 'Europe/Moscow') AS time,\r\n    price AS NVDA\r\nFROM default.Stocks_Price\r\nWHERE symbol = 'NVDA'\r\nORDER BY time ASC",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Google (GOOGL)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "contextWindowSize": "10",
     "formattedQuery": "/* grafana dashboard='Stocks Live', user=1 */\nSELECT\r\n    toTimeZone(parseDateTimeBestEffort(timestamp), 'Europe/Moscow') AS time,\r\n    price AS GOOGL\r\nFROM default.Stocks_Price\r\nWHERE symbol = 'GOOGL'\r\nORDER BY time ASC",
     "query": "SELECT\r\n    toTimeZone(parseDateTimeBestEffort(timestamp), 'Europe/Moscow') AS time,\r\n    price AS GOOGL\r\nFROM default.Stocks_Price\r\nWHERE symbol = 'GOOGL'\r\nORDER BY time ASC",
     "round": "0s"
    }
   ]
  }
 ]
}